name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  ssh-deploy:
    name: Deploy Backend via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy backend files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.BE_SSH_HOST }}
          username: ${{ secrets.BE_SSH_USER }}
          key: ${{ secrets.BE_SSH_KEY }}
          source: "backend/*"
          target: "/home/user/backend/"

      - name: Run deploy script on server
        uses: appleboy/ssh-action@v1.1.1
        with:
          host: ${{ secrets.BE_SSH_HOST }}
          username: ${{ secrets.BE_SSH_USER }}
          key: ${{ secrets.BE_SSH_KEY }}
          script: |
            cd /home/user/backend/
            chmod +x deploy.sh
            ./deploy.sh
